version: '3'

services:
  mysql:
    container_name: "test_mysql222"
    image: mysql/mysql-server:latest
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"
